OrdererOrgs:
  - Name: Orderer
    Domain: grambank.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: GramBank
    Domain: grambank.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
