---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../crypto-config/ordererOrganizations/grambank.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &GramBankOrg
    Name: GramBankMSP
    ID: GramBankMSP
    MSPDir: ../crypto-config/peerOrganizations/grambank.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('GramBankMSP.admin', 'GramBankMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('GramBankMSP.admin', 'GramBankMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('GramBankMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('GramBankMSP.member')"
    AnchorPeers:
      - Host: peer0.grambank.com
        Port: 7051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.grambank.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.grambank.com
        Port: 7050
        ClientTLSCert: ../crypto-config/ordererOrganizations/grambank.com/orderers/orderer.grambank.com/tls/server.crt
        ServerTLSCert: ../crypto-config/ordererOrganizations/grambank.com/orderers/orderer.grambank.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

Profiles:
  GramBankChannelGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *GramBankOrg

  GramBankChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *GramBankOrg
      Capabilities:
        <<: *ApplicationCapabilities
